ebms_print_job_type.type.*:
  type: config_entity
  label: Print Job Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    description:
      type: string
      label: Description
