ebms_internal_tag.tag.*:
  type: config_entity
  label: Internal Tag Value
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    active:
      type: boolean
      label: Active
